### ISSUE TITLE
Make a standard way to write pseudocode

### ISSUE THREAD

**Issue by Alaz-Oz** [2G-Labs/DSA#1]
# Problem we face now
What we do now is write pseudocode in different fashions, that leads to confusion, and non-uniform code in the repository. 

# General idea for the solution

We should make a standard for writing pseudocode that is
- Beautiful
- Easier to understand
- Could be implemented at ease in any language

**Comment by Alaz-Oz** [comment]
### Suggested Pseudocode Standardization Template:

#### 1. **Naming Conventions:**
- Use descriptive variable names that convey the purpose.
- Follow snake_case for variable naming for easy readability.

#### 2. **Indentation and Structure:**
- Use 4 space indentation for improved readability.
- Maintain a clear structure with logical blocks (if-else, loops) indented properly.

#### 3. **Comments and Documentation:**
- Provide comments to explain complex sections or logic. ( Start comments with # )
- Use clear and concise comments to describe the purpose of variables, functions, and major steps.

#### 4. **Variables and Data Types:**
- Declare variables explicitly and initialize them where applicable.
- Specify data types (integers, floats, strings, etc.) for better understanding.

#### 5. **Control Structures:**
- Use clear control structures (if-else, loops) with proper conditions.
- Label loops and provide exit conditions where needed for readability.

#### 6. **Functions and Procedures:**
- Define functions or procedures with clear names, input parameters and its output type.
- Provide function headers with descriptions, parameters, and return types (if applicable).

#### 7. **Error Handling:**
- Include error handling mechanisms where appropriate.
- Indicate potential error cases and how they're handled within the pseudocode.

#### 8. **Consistency with Algorithms:**
- Align the pseudocode with the logic of the underlying algorithm.
- Ensure that the pseudocode accurately represents the algorithm's steps.

#### 9. **Use of Standard Notations:**
- Use commonly accepted symbols for mathematical operations, comparisons, etc.

#### Example Template:

```plaintext
# Algorithm Name: Brief Description

# Initialize variables
variable_1 = value
variable_2 = value

# Function/Procedure Definitions
function_name(parameter_1, parameter_2):
    # Function logic
    ...

    # Main algorithm steps
    for i = 1 to n:
        if condition:
            perform action_1
        else:
            perform action_2

    # Final output or return statement
    return result
```

# I am open to suggestions and improvement.

**Comment by Alaz-Oz** [comment]
@2G-Afroz Could you review and suggest some changes before finalization

**Comment by 2G-Afroz** [comment]
1. Naming Conventions:
Follow camelCase for variable and function naming.
Follow PascalCase for class naming.
For concise and short naming.

**Comment by Alaz-Oz** [comment]
# @2G-Afroz Anything else?
We should have a standard for the data structure also. Could you suggest anything?
